import Head from 'next/head';
import Link from 'next/link';
import React, { useEffect } from 'react';
import { MdAddBox } from 'react-icons/md';
import { BiLogOut } from 'react-icons/bi';
import { Login_data } from '../context/context';
import { useContext } from 'react';
import Cookies from 'js-cookie';
import axios from 'axios';

const LayoutScreen = ({ children, title }) => {
    const { loginUser, setloginUser } = useContext(Login_data);

    const logoutfunction = () => {
        Cookies.remove('isLoggedIn');
    }

    useEffect(() => {
        const checkUserLogin = async () => {
            if (Cookies.get('isLoggedIn')) {
                let storedUser = JSON.parse(Cookies.get('isLoggedIn'));
                if (!loginUser) {
                    const userResponse = await axios.post('http://localhost:3000/api/login', storedUser);
                    if (storedUser.email === userResponse.data.email && storedUser.password === userResponse.data.password) {
                        setloginUser(true);
                        return;
                    }
                    else {
                        Cookies.remove('isLoggedIn');
                    }
                }
            }
        }
        checkUserLogin();
    }, [])

    return (
        <div >
            <header>
                <Head>
                    <title> {title ? `${title}-Note-App` : `Note App`} </title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <nav className='shadow-md'>
                    <div className='px-5 py-3 flex items-center justify-between max-w-screen-lg mx-auto container'>
                        <div>
                            <Link href="/"><span className='text-xl font-bold'>Note App</span></Link>
                        </div>
                        <ul className='flex space-x-5 items-center'>
                            <li className='text-lg font-bold'><Link href='/jspage'>Js</Link></li>
                            <li className='text-lg font-bold'><Link href='/tspage'>Ts</Link></li>
                            <li className='text-lg font-bold'><Link href='/nodepage'>Node</Link></li>
                            <li className='text-lg font-bold'><Link href='/newnote'>{<MdAddBox />}</Link></li>
                            <li className='text-lg font-bold' onClick={logoutfunction}><a href="/">{loginUser && <BiLogOut />}</a></li>
                        </ul>
                    </div>
                </nav>
            </header>
            <main className='px-5 py-4 max-w-screen-lg mx-auto container'>
                {children}
            </main>
            <footer className='px-5 max-w-screen-lg mx-auto container text-center'>
                <p>All rights are reserved @2023</p>
            </footer>
        </div>
    )
}

export default LayoutScreen
